### ISSUE TITLE
display the same name as host which is under k8s.node.name

### ISSUE THREAD

**Issue by pszkamruk-splunk** [signalfx/splunk-otel-collector#1043]
After installing splunk-otel-collector to monitor sc4snmp microk8s logs we are getting host field equal "localhost" but instead we should get the value which is kept under: `k8s.node.name | ip-10-202-37-181`

**Comment by rmfitzpatrick** [comment]
@pszkamruk-splunk would you be able to explain in a bit more detail what you're seeing and why you have a different expectation? Sharing a collector configuration for the deployment in question could also be helpful.

**Comment by pszkamruk-splunk** [comment]
@rmfitzpatrick 
here is the link which redirects to installation instructions
https://splunk.github.io/splunk-connect-for-snmp/main/gettingstarted/sck-installation/
In sc4snmp we are using splunk-otel-collector as a solution which grabs sc4snmp logs (sc4snmp is installed on microk8s)  and then sends those logs into splunk which under different ip address than sc4snmp connector
As a result logs are being sent to splunk correctly but host field is incorrect, we are receiving localhost instead of sc4snmp hostname.
The correct value of hostname (ie. `ip-10-202-37-181`) is present under `k8s.node.name`

**Comment by rmfitzpatrick** [comment]
Not being familiar with connect for snmp it sounds like the field could be set there? If you know the desired host value to use from the collector config you could use an attributes processor: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/attributesprocessor. However, I don't believe this is an issue with our collector distribution. It is likely specific to your environment or potentially a collector helm chart configuration question or issue: https://github.com/signalfx/splunk-otel-collector-chart.
