### ISSUE TITLE
splunk-support-bundle.ps1 fails if Fluentd is not installed or Fluentd Windows Service is not running

### ISSUE THREAD

**Issue by bxtp4p** [signalfx/splunk-otel-collector#1155]
To repro:

Install the collector to a Windows machine. After installation, stop the Fluentd Windows Service. Then try running the `splunk-support-bundle.ps1` script. You get the following error:

```
Get-Process : Cannot find a process with the name "ruby". Verify the process name and call the cmdlet again.
At C:\Program Files\Splunk\OpenTelemetry Collector\splunk-support-bundle.ps1:245 char:9
+         Get-Process -Name 'ruby' | Where-Object {$_.Path -eq "${env:S ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (ruby:String) [Get-Process], ProcessCommandException
    + FullyQualifiedErrorId : NoProcessFoundForGivenName,Microsoft.PowerShell.Commands.GetProcessCommand 

```

**Comment by jcheng-splunk** [comment]
Thanks @bxtp4p for reporting this.  You can download the updated script from https://github.com/signalfx/splunk-otel-collector/blob/main/internal/buildscripts/packaging/msi/splunk-support-bundle.ps1, and it should be included in the next release.  Please close this issue if this issue is resolved.
