### ISSUE TITLE
Environment variables not ideal when running the collector as a windows service

### ISSUE THREAD

**Issue by jchengsfx** [signalfx/splunk-otel-collector#122]
Currently, the collector requires specific environment variables to be defined unless the required values are explicitly set in the config.  However, there is not an intuitive way for a user to pass env vars to the collector when running the collector as a windows service.

One suggestion is to allow the collector config to load values from a separate file, similar to the smart agent (see https://github.com/signalfx/signalfx-agent/blob/master/docs/remote-config.md and https://github.com/signalfx/signalfx-agent/blob/master/packaging/win/agent.yaml).

**Comment by pjanotti** [comment]
What about giving instructions to use `reg add` from the command prompt? Is it intuitive enough?

**Comment by pjanotti** [comment]
BTW, see the bottom of this change on SFx.NET via this PR: https://github.com/signalfx/signalfx-dotnet-tracing/pull/93

**Comment by jchengsfx** [comment]
> BTW, see the bottom of this change on SFx.NET via this PR: [signalfx/signalfx-dotnet-tracing#93](https://github.com/signalfx/signalfx-dotnet-tracing/pull/93)

Thanks @pjanotti .  Yes, I was able to get the collector service working when I add the env vars to `HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment`.
