### ISSUE TITLE
Provide a easy-to-setup configuration to run a collector locally for developers

### ISSUE THREAD

**Issue by jkwatson** [signalfx/splunk-otel-collector#138]
As a OpenTelemetry developer, I'd like to have an easy-to-run configuration/example to run a copy of the collector locally and send data to the Splunk backends. I tried using the docker-compose example, but it didn't include a config file, nor any instructions on how to use it.

**Comment by flands** [comment]
@jkwatson does this work: https://github.com/signalfx/splunk-otel-collector/blob/main/docs/getting-started/linux-standalone.md#docker?

**Comment by jkwatson** [comment]
I'll give it a try!

**Comment by jkwatson** [comment]
Yes, that is great. Thanks!
