### ISSUE TITLE
import `stdout` operator in filelog receiver operators

### ISSUE THREAD

**Issue by matthewmodestino** [signalfx/splunk-otel-collector#1400]
As a user of OTel native logging, it would be very helpful for debugging and user enablement, if I could use the `stdout` operator in the splunk otel collector to examine the entries as they pass through various filelog receiver operators. We frequently need to create custom operators to transform log entries and it is extremely difficult when it is not clear to users what the entries look like as they flow in through the filelog receiver and through the operators. 

https://github.com/open-telemetry/opentelemetry-log-collection/blob/main/docs/operators/stdout.md

I attempted adding it to my pipeline and I get an error advising unsupported operator.

**Comment by atoulme** [comment]
This operator is also unsupported by the opentelemetry-collector-contrib repository. I think it would be best to raise the issue there directly to get this operator available upstream.

**Comment by atoulme** [comment]
This has now been reported upstream. Closing this issue in favor of the issue upstream.
