### ISSUE TITLE
splunk_hec/platform_logs  Exporting failed. Will retry the request after interval  "error EOF"

### ISSUE THREAD

**Issue by matthewmodestino** [signalfx/splunk-otel-collector#1453]
Hey team, 

In working with customers who are sending logs from OTel through a client managed Load Balancer (mostly f5s so far) to Splunk "Heavy Forwarders" and are seeing "EOF" errors on their logging exporters:

```
2022-04-05T12:55:27.607Z info exporterhelper/queued_retry.go:215 Exporting failed. Will retry the request after interval. {"kind": "exporter", "name": "splunk_hec/platform_logs", "error": "Post \"https://foo.bar.com:8088/services/collector\": EOF", "interval": "3.985412818s"}
2022-04-04T16:39:44.614Z    info    exporterhelper/queued_retry.go:218    Exporting failed. Will retry the request after interval.    {"kind": "exporter", "name": "splunk_hec/platform_logs", "error": "Post \"https://foo.bar.com:443/services/collector/event\": EOF", "interval": "4.623187485s"} 
```
In my digging on the internet, it looks like OTel will try and reuse connections and that they may have been closed by the far end (either the LB or Splunk, I'm still trying to prove either). 

Could use a hand with some guidance on what might be causing this or how to tune OTel, the LB or Splunk to resolve. 

Could this be an opportunity for tuning the `max_connections` we use on the daemonset to ensure we aren't overwhelming the LB or Splunk?

https://github.com/signalfx/splunk-otel-collector-chart/blob/97dc6dca6f04a764a1fe48658453de72ed747a35/helm-charts/splunk-otel-collector/values.yaml#L43-L44

What can we look at to attempt to tune the LB or Spunk side?

**Comment by matthewmodestino** [comment]
Looks like both users are sending through an f5 with default TCP settings:

```
idle timeout : 300 s
keepalive: 1800 s
time wait : 2000 ms
```

https://support.f5.com/csp/article/K29377715
https://support.f5.com/csp/article/K13004262

I believe this, in conjunction with the `busyKeepAliveIdleTimeout` HTTP input setting on Splunk side may be the issue:

```
keepAliveIdleTimeout = <integer>
* How long, in seconds, that the HTTP Event Collector input lets a keep-alive
  connection remain idle before forcibly disconnecting it.
* If this value is less than 7200, the input sets it to 7200.
* Default: 7200

busyKeepAliveIdleTimeout = <integer>
* How long, in seconds, that the HTTP Event Collector lets a keep-alive
  connection remain idle while in a busy state before forcibly disconnecting it.
* CAUTION: Setting this to a value that is too large
  can result in file descriptor exhaustion due to idling connections.
* If this value is less than 12, the input sets it to 12.
* Default: 12
```

I know we commonly tweak the `busyKeepAliveIdleTimeout` to a setting higher than the LB, but will need to keep digging to prove if this is the root cause of the `EOF`

**Comment by harshit-splunk** [comment]
The client will throw an `EOF` error when the server has closed the connection and the client is using still sending packets to the closed connection. It can happen when the client's keep-alive timeout is greater or equal to the server's keep-alive timeout.
OTel agent has a fixed keep-alive timeout of the 30s. I suggest revisiting the splunk and load balancer's timeout configs.
Also. we should close it as it looks like it's not collector specific issue.

**Comment by atoulme** [comment]
We can close it, would you please open issues upstream?

**Comment by matthewmodestino** [comment]
Did we create an issue for this upstream?

Need to reopen this after some recent testing.

Need the HEC exporter to provide configurable http idle timeout similar to what we used for fluentd-hec

https://github.com/splunk/fluent-plugin-splunk-hec#idle_timeout-integer

In previous threads I believe we found OTel collector had a 30 second hardcoded timeout. We need this to be lower by default to avoid re-using connections that are torn down, which causes the EOF.

Splunk's default timeout for "busy idle connections" is 12 seconds.

We need it set like fluentd-hec by default to avoid the EOFs which we never saw.

**Comment by matthewmodestino** [comment]
Submitted up stream issue [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/20543)

**Comment by atoulme** [comment]
We made this configurable - and our timeout is now 10s by default, but not sure that is the same as the idle timeout. More testing required.

**Comment by atoulme** [comment]
Workaround, the exporter takes the key `idle_conn_timeout` to set the value.

You can set like so:
```
exporters:
  splunk_hec/foo:
    ...
    idle_conn_timeout: 10s
```
