### ISSUE TITLE
jmx monitor: Could not initialize class sun.security.ssl.SSLContextImpl$DefaultSSLContext

### ISSUE THREAD

**Issue by tchernomax** [signalfx/splunk-otel-collector#1543]
I am unable to use the JMX receiver with ssl enabled (which keyStore… and trustStore… variables set).
The container logs shows:
```
Could not initialize class sun.security.ssl.SSLContextImpl$DefaultSSLContext
```

It seems the container image misses a java class.

I am using https://github.com/signalfx/splunk-otel-collector-chart/blob/splunk-otel-collector-0.44.1/helm-charts/splunk-otel-collector/Chart.yaml (because I run k8s 1.19) which use quay.io/signalfx/splunk-otel-collector:0.44.0 .

I didn't test with the latest container image version.

**Comment by rmfitzpatrick** [comment]
I think something akin to this is necessary in our dockerfile, which should be added w/ an integration test (cc @jeffreyc-splunk).

```
FROM openjdk:11 as openjdk
...
ENV JAVA_HOME=/usr/lib/splunk-otel-collector/agent-bundle/jre
...
COPY --from=openjdk --chown=999 /usr/local/openjdk-11/conf /usr/lib/splunk-otel-collector/agent-bundle/jre/conf
```
