### ISSUE TITLE
SELinux and Splunk-Otel-Collector 

### ISSUE THREAD

**Issue by rss04** [signalfx/splunk-otel-collector#1695]
Hi,

Do we need any special permissions for making Splunk-Otel-Collector run in SELinux environment with permissive mode ? 
I was able to install but not able to start the splunk-otel-collector in Centos SELinux (permissive mode) environment. 
I am receiving this error:
Job for splunk-otel-collector.service failed because a configured resource limit was exceeded. 

Any help or pointers on where to look is really appreciated. Thanks in advance.

**Comment by atoulme** [comment]
Closing this conversation. Please reopen if further clarification or work is needed.
