### ISSUE TITLE
High increase in indexer queue used percentage when switching to otel

### ISSUE THREAD

**Issue by tqi-raurora** [signalfx/splunk-otel-collector#1873]
We've been using splunk connect for kubernetes for some time.
We've tried switching to otel, however when we switched we saw some increase in the GBs ingested coming from kubernetes, along with a very big increase in the % used rate for the queues in our indexers.

We are wondering where this increase in indexer load might be coming from. The ingestion in GBs doesn't seem big enough to cause the huge increase in queue usage that we are seeing.

Here's a hypothesis: We've noted that otel by default sends some new metadada to splunk, in particular this field: k8s.container.restart_count, that gingested as an indexed field, at index time.

Is it possible that by trying to index k8s.container.restart_count or other metadata as an indexed field, splunk is suffering a higher load?
Is it possible to stop otel from sending metadata? Our alternatively, is it possible to make splunk ignore this metadata?

Thanks in advance

**Comment by atoulme** [comment]
Hello! I have seen your original post in https://github.com/signalfx/splunk-otel-collector-chart/issues/503. I am going to close this issue and will follow up there.
