### ISSUE TITLE
Installation script production use clarification

### ISSUE THREAD

**Issue by mukundbabbar** [signalfx/splunk-otel-collector#1876]
The installation script mentions that it is "not recommended for production use". Is this still valid? 

<img width="533" alt="Screen Shot 2022-08-14 at 3 06 54 am" src="https://user-images.githubusercontent.com/5012739/184542866-e735cdbb-b830-4910-ab65-d650561ef086.png">

<img width="763" alt="Screen Shot 2022-08-15 at 1 00 15 am" src="https://user-images.githubusercontent.com/5012739/184542882-0ae5a5ca-4cd2-45a5-bc53-c14d630823f6.png">

Thanks

**Comment by jeffreyc-splunk** [comment]
Thanks @mukundbabbar.  The doc and script has been updated.
