### ISSUE TITLE
Issue installing this on a hybrid OpenShift 4.11 cluster with Windows Server 2022 workers

### ISSUE THREAD

**Issue by rprakashg-redhat** [signalfx/splunk-otel-collector#2075]
I'm working with a customer who is trying to install this on a hybrid cluster running OpenShift 4.11 with windows server 2022 on worker nodes. Documentation says its supported on OpenShift but doesnt really say which version also doesn't mention version of Windows Server supported on worker nodes. 

Instructions for windows deployment is missing some config required for scheduler to schedule the daemonset on windows nodes 
as described in this document here https://docs.openshift.com/container-platform/4.11/windows_containers/scheduling-windows-workloads.html

after adding this in values.yaml 
```
- key: "os"
      operator: "Equal"
      value: "windows"
      effect: "NoSchedule"
```

we can see the workload getting scheduled on windows nodes but container doesn't start up because of the windows version mismatch between the container and host worker machine

Just logging this here as an enhancement request to support windows server 2022 and also update missing information in documentation. I'm willing to work on this but wanted to reach out here first to see if this is already in the works or not

**Comment by atoulme** [comment]
Thank you for your report!
Did you mean to report this issue on https://github.com/signalfx/splunk-otel-collector-chart ? This seems related to our helm chart as you mention a values.yaml file.

**Comment by rprakashg-redhat** [comment]
Not sure. What needs to happen is who ever maintains this image https://quay.io/repository/signalfx/splunk-otel-collector-windows needs to release a new version that supports windows server 2022. Currently this is the image that is being used and we can see in errors the about the version mismatch

**Comment by rprakashg-redhat** [comment]
Agree doc update that needs to be made to add the above config in values yaml needs to go to the chart repo but the main issue around support for windows server 2022 still would be here IMO

**Comment by atoulme** [comment]
OK I understand better. Thank you for clarifying.

**Comment by rprakashg-redhat** [comment]
Perhaps I should have created two separate issues :) Sorry if I confused

**Comment by atoulme** [comment]
We have identified this issue as an enhancement and will look at supporting a Windows 2022 image. This is also reported in https://github.com/signalfx/splunk-otel-collector-chart/issues/551

**Comment by atoulme** [comment]
Windows 2022 docker images are now supported. Closing this issue and will follow up with Openshift issues, if any, in the chart repository.
