### ISSUE TITLE
Issue: protobuf-cpp and protobuf-python have potential Denial of Service issue reported for v0.58.0

### ISSUE THREAD

**Issue by kumachop2** [signalfx/splunk-otel-collector#2148]
The parsing and memory management vulnerability in ProtocolBuffer’s C++ and Python implementations can trigger an out of memory (OOM) failure when processing a specially crafted message, which could lead to a denial of service (DoS) on services using the libraries.

Affected  version is >= 3.20.0, < 3.20.2 and patched version should be 3.20.2

Issue reported with Splunk Otel Collector v0.58.0 and I did verify v0.61.0 also bundled with same version of package. Please let me know the timelines for fixed version of Splunk Otel Collector.

./usr/lib/splunk-otel-collector/agent-bundle/lib/python3.8/site-packages/protobuf-3.20.1-py3.8-nspkg.pth

**Comment by rmfitzpatrick** [comment]
@kumachop2 thanks for reporting this. The [most recent version](https://github.com/signalfx/splunk-otel-collector/releases/tag/v0.63.0) now picks up protobuf 3.20.3 from the Smart Agent bundle.
