### ISSUE TITLE
Outdated Kubernetes instructions

### ISSUE THREAD

**Issue by juandspy** [signalfx/splunk-otel-collector#2213]
### Summary

I tried deploying the Kubernetes version of the collector ([this one](https://github.com/signalfx/splunk-otel-collector/blob/8578955e71e77decc56720d0e1b71d699b82948b/examples/kubernetes-yaml/splunk-otel-collector-gateway.yaml)) and it gives me the following error:
```
2022/11/02 11:31:48 settings.go:269: Set config to [/conf/otel-collector-config.yaml]
2022/11/02 11:31:48 settings.go:333: Set ballast to 168 MiB
2022/11/02 11:31:48 settings.go:349: Set memory limit to 460 MiB
Error: unknown flag: --mem-ballast-size-mib
2022/11/02 11:31:48 main.go:99: application run finished with error: unknown flag: --mem-ballast-size-mib
```

What do we have to do with [that flag](https://github.com/signalfx/splunk-otel-collector/blob/8578955e71e77decc56720d0e1b71d699b82948b/examples/kubernetes-yaml/splunk-otel-collector-gateway.yaml#L205)?

Related PRs: https://github.com/signalfx/splunk-otel-collector/pull/567

### How to reproduce

```
❯ docker run --rm -e SPLUNK_REALM=us1 -e SPLUNK_ACCESS_TOKEN=test quay.io/signalfx/splunk-otel-collector:0.62.0 /otelcol --mem-ballast-size-mib=168
2022/11/02 11:33:20 settings.go:286: Set config to /etc/otel/collector/gateway_config.yaml
2022/11/02 11:33:20 settings.go:333: Set ballast to 168 MiB
2022/11/02 11:33:20 settings.go:349: Set memory limit to 460 MiB
Error: unknown flag: --mem-ballast-size-mib
2022/11/02 11:33:20 main.go:99: application run finished with error: unknown flag: --mem-ballast-size-mib
```

**Comment by atoulme** [comment]
Thank you for your report. We have since created a complete helm chart you might prefer to use to deploy the collector. Please see https://github.com/signalfx/splunk-otel-collector-chart.

We will look at updating or deleting this example.

**Comment by juandspy** [comment]
@atoulme thanks. For me it was easier to use this template with a config map, service and deployment. It worked like a charm removing the `--mem-ballast-size-mib` flag.
