### ISSUE TITLE
Exporting failed. Will retry the request after interval

### ISSUE THREAD

**Issue by RPooja08** [signalfx/splunk-otel-collector#2243]
We are getting this error "Exporting failed. Will retry the request after interval" very randomly on random servers for short duration. Due to this error, the data stopped reporting for that duration. We have checked the network logs and flow but there is no issue with that.
Can anyone help on this.

**Comment by atoulme** [comment]
Please open a support case as this might be an issue with your backend. Please add to the support ticket a description of your environment, such as your version of the collector used, and the destination information (Splunk Cloud, Splunk Observability).
