### ISSUE TITLE
SignalFx Smart Agent -> Receivers link is broken

### ISSUE THREAD

**Issue by jshawatsplunk** [signalfx/splunk-otel-collector#2377]
Under Advanced Configuration: https://github.com/signalfx/splunk-otel-collector#advanced-configuration
SignalFx Smart Agent
Receivers -> points to here: https://github.com/signalfx/splunk-otel-collector/tree/main/pkg/receiver/smartagentreceiver which returns a 404

**Comment by atoulme** [comment]
Thank you, it should be https://github.com/signalfx/splunk-otel-collector/tree/main/pkg/receiver/smartagent instead.
