### ISSUE TITLE
prometheusremotewrite not supported

### ISSUE THREAD

**Issue by elvis-cai** [signalfx/splunk-otel-collector#2398]
Hi guys, is it expected that we can not use prometheusremotewrite to export metrics to our managed prometheus endpoint?
Here's the error I get 
```
error decoding 'exporters': unknown exporters type: "prometheusremotewrite" for id: "prometheusremotewrite" (valid values: [file sapm splunk_hec kafka logging otlp otlphttp signalfx httpsink pulsar])
```

**Comment by awx-kevinli** [comment]
A splunk support case `#3119248` is created with association to this issue as well

**Comment by atoulme** [comment]
The prometheusremotewrite receiver is not yet merged in OpenTelemetry. Here is the PR: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/14752

We will be happy to support it if we can package it, install with it and test against it.

**Comment by atoulme** [comment]
Please use the support case for further communications.
