### ISSUE TITLE
k8s cluster receiver uses to be removed k8s API kinds

### ISSUE THREAD

**Issue by duritong** [signalfx/splunk-otel-collector#2457]
Currently the otel-collector requests `batch/v1beta1 CronJob` and `autoscaling/v2beta2 HorizontalPodAutoscaler` from the API

These API kinds in that API version are going to be removed in k8s 1.25: 

* https://kubernetes.io/docs/reference/using-api/deprecation-guide/#cronjob-v125
* https://kubernetes.io/docs/reference/using-api/deprecation-guide/#horizontalpodautoscaler-v125

This is with otel 0.67.0

**Comment by atoulme** [comment]
Thank you for the report. We'll take a look and report upstream as needed.

**Comment by jvoravong** [comment]
Okay, that is a warning and not an error I would worry about. Kubernetes 1.25 still shows this warning, as HPA is unavailable in 1.26.

> W0329 13:46:57.771692    1 warnings.go:70] autoscaling/v2beta2 HorizontalPodAutoscaler is deprecated in v1.23+, unavailable in v1.26+; use autoscaling/v2 HorizontalPodAutoscaler

Back in April of 2022 we prepared for this.

- The collectors starts up and checks what versions of HorizontalPodAutoscaler are available in the cluster to monitor.
- We use the beta versions if they are available in the cluster to support older clusters, when we do this that warning generates. It is not an error though.
- If the beta versions are not available, we use the later v1 or current versions.

I’m going to close that issue.
