### ISSUE TITLE
reference -https://github.com/signalfx/splunk-otel-collector/issues/2426

### ISSUE THREAD

**Issue by Davinder2609** [signalfx/splunk-otel-collector#2512]
reference -https://github.com/signalfx/splunk-otel-collector/issues/2426

**Comment by Davinder2609** [comment]
using >promethues-fedration code
getting error- 

otelcollector  | 2023-01-25T19:08:33.763Z       info    exporterhelper/queued_retry.go:427      Exporting failed. Will retry the request after interval.        {"kind": "exporter", "data_type": "metrics", "name": "splunk_hec/metrics", "error": "Post \"https://splunk:8088/services/collector\": dial tcp 172.22.0.4:8088: connect: connection refused", "interval": "5.021810571s"}
otelcollector  | 2023-01-25T19:08:33.796Z       info    exporterhelper/queued_retry.go:427      Exporting failed. Will retry the request after interval.        {"kind": "exporter", "data_type": "metrics", "name": "splunk_hec/metrics", "error": "Post \"https://splunk:8088/services/collector\": dial tcp 172.22.0.4:8088: connect: connection refused", "interval": "14.480459587s"}
splunk         |

**Comment by atoulme** [comment]
Reopening #2426.
