### ISSUE TITLE
Update Journald receiver docs to mention support of "operators"

### ISSUE THREAD

**Issue by matthewmodestino** [signalfx/splunk-otel-collector#2570]
Hey Team!

Recently we were playing with the journald receiver as part of the splunk otel helm chart, and noticed it used `operators`. This was confusing as the journald receiver docs dont mention support of `operators`. 

https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/journaldreceiver

Please update journald receiver docs to reflect that you can use operators like we do in the helm chart. 

FYI, I deployed with journald receiver and confirmed in the configmap that the `operators` do in fact seem to work

**Comment by atoulme** [comment]
Work continues upstream. Please follow the ticket upstream, I will close this ticket now.
