### ISSUE TITLE
Create docs for upgrading the collector on Windows hosts with Chocolatey

### ISSUE THREAD

**Issue by jvoravong** [signalfx/splunk-otel-collector#2578]
When installing on WIndows with [Chocolatey](https://github.com/signalfx/splunk-otel-collector/blob/561c3cf516405e0a15f3a4b6a81b71e12a6f5163/docs/getting-started/windows-manual.md#chocolatey-installation) (how I do it), we should have docs for how to do an install but not an upgrade. I would like to have docs for how to upgrade the collector on Windows when using Chocolatey.

AC:
- Make sure to highlight that we have to set an install parameter when installing the Collector so that Chocolatey remembers previous release configurations when upgrading the collector.
  - From the [internet](https://superuser.com/questions/1277968/how-can-i-upgrade-a-chocolatey-package-if-its-already-installed-and-install-it)
  - `choco feature enable -n=useRememberedArgumentsForUpgrade`
- Have docs and examples for the Chocolatey upgrade splunk-otel-collector steps to show users how to do it.

**Comment by atoulme** [comment]
@theletterf please let us know if this something your team can take up maybe in the next quarter.

**Comment by aurbiztondo-splunk** [comment]
@atoulme - We already have https://signalfuse.atlassian.net/browse/DOCS-5041 waiting. If you have the bandwidth for this, we can include our task to PI2 as well.

**Comment by atoulme** [comment]
Closing, work continues with the link provided.
