### ISSUE TITLE
Environment variable resolution is broken when SPLUNK_DOUBLE_DOLLAR_CONFIG_SOURCE_COMPATIBLE is false

### ISSUE THREAD

**Issue by crobert-1** [signalfx/splunk-otel-collector#2628]
Versions: v0.71.0+

This is a result of [this change.](https://github.com/open-telemetry/opentelemetry-collector/pull/7055). The current impact is shown by the `TestIncompatibleExpandedDollarSignsViaEnvConfigSource` integration test.

Failing config section:
```
          - action: add_label
            new_label: double-dollar
            new_value: $${env:AN_ENVVAR}-suffix
```

The config resolution logic attempts to resolve the environment variable successfully, but rather than setting a config map up with the key value of the environment variable name as key, and environment value as the value, it simply creates a string of the environment variable value. This results in a panic when attempting to start the collector because it's attempting to merge a map with a string.

Panic location [here.](https://github.com/signalfx/splunk-otel-collector/blob/main/internal/configprovider/config_source_provider.go#L80)

Possible solutions include:

1. replacing the wrapped config provided entirely and just using core's.
2. Modifying the [Retrieve method's ](https://github.com/signalfx/splunk-otel-collector/blob/main/internal/configprovider/config_source_provider.go#L62) logic to properly handle environment variables, and plain strings to merge them into a map. We'd have to be pretty careful with the second option as the config resolution logic is pretty involved, so just modifying values would be pretty risky.

**Comment by crobert-1** [comment]
[This line](https://github.com/signalfx/splunk-otel-collector/blob/a80918616cea51f830e9f28ef061ebff7a37b0ad/internal/configprovider/config_source_provider.go#L66) is what ends up converting the environment variable value to a string of its own value. This call could either be replaced, modified, or the result could be edited to be the proper format. This would be if we chose option 2 in the description.

This is the `Retrieve` [method that properly gets the env variable value.](https://github.com/open-telemetry/opentelemetry-collector/blob/ee4fc5694ca2656b0128ae86b115887bc9f88ab6/confmap/provider/envprovider/provider.go#L39) This method has an equivalent for file sources, HTTP, etc. These would all have to be properly handled if the second option is chosen.

**Comment by rmfitzpatrick** [comment]
Resolved by https://github.com/signalfx/splunk-otel-collector/commit/70b75c75a2d99f9c968fc1f2fec01ce5f0a6fa84
