### ISSUE TITLE
Feature Request: command line option for `NO_WINDOWS_SERVICE` env var

### ISSUE THREAD

**Issue by rockb1017** [signalfx/splunk-otel-collector#2643]
I am working on otel TA for Splunk Universal Forwarder. 
We are having some trouble for windows service account that runs Splunk but doesn't have permission to change env var.
It would be great if `NO_WINDOWS_SERVICE` feature can be controlled some other way than env var such as command line option.

**Comment by atoulme** [comment]
Closing for now as this is no longer in scope of work, the work will continue upstream.
