### ISSUE TITLE
Provided journald.conf assumes /run/log/journal exists, often doesn't.

### ISSUE THREAD

**Issue by mkohner-repay** [signalfx/splunk-otel-collector#2669]
internal/buildscripts/packaging/fpm/etc/otel/collector/fluentd/conf.d/journald.conf

references `/run/log/journal` which actually may not always exist. This results in td-agent.log filling up errors.
```2023-03-07 22:25:13 +0000 [warn]: #0 Systemd::JournalError: No such file or directory retrying in 1s```
Issue seen on both Ubuntu 18.04 and AL2.

**Comment by jeffreyc-splunk** [comment]
@mkohner-repay Please refer to the post-install configuration note in https://github.com/signalfx/splunk-otel-collector/blob/main/docs/getting-started/linux-installer.md#fluentd-configuration:

>By default, Fluentd will be configured to collect log events from many popular services, like the systemd journal. Check the .conf files in this directory for the default configuration of the included sources. Note: The paths defined within these sources may need to be updated for the system or service.

Also, please see #516 for why we set the default path to `/run/log/journal`.

**Comment by atoulme** [comment]
Closing as answered. Please reopen or comment if more work is required.
