### ISSUE TITLE
Add support for Rockylinux and Almalinux in the linux installer script splunk-otel-collector.sh

### ISSUE THREAD

**Issue by williake** [signalfx/splunk-otel-collector#2753]
Would it be possible to add support for rockylinux and almalinux in the linux installer script: splunk-otel-collector.sh ?

Currently we get an error message when trying to install splunk-otel-collector on rockylinux

**Comment by williake** [comment]
I added checks in the installer script if the "ID_LIKE" contains "rhel" in /etc/os-release in this pull request(https://github.com/signalfx/splunk-otel-collector/issues/2753) (I'm not completely sure how to link issues and pull requests on github)


Where "ID_LIKE" is:

    A space-separated list of operating system identifiers in the same syntax as the ID= setting. It should list identifiers of operating systems that are closely related to the local operating system in regards to packaging and programming interfaces, for example listing one or more OS identifiers the local OS is a derivative from. An OS should generally only list other OS identifiers it itself is a derivative of, and not any OSes that are derived from it, though symmetric relationships are possible. Build scripts and similar should check this variable if they need to identify the local operating system and the value of ID= is not recognized. Operating systems should be listed in order of how closely the local operating system relates to the listed ones, starting with the closest. This field is optional.

    Examples: for an operating system with "ID=centos", an assignment of "ID_LIKE="rhel fedora"" would be appropriate. For an operating system with "ID=ubuntu", an assignment of "ID_LIKE=debian" is appropriate. 

source: "https://www.freedesktop.org/software/systemd/man/os-release.html"

**Comment by atoulme** [comment]
Thank you, we will review your PR and get back to you.

**Comment by rmfitzpatrick** [comment]
Closing per https://github.com/signalfx/splunk-otel-collector/pull/2764#issuecomment-1759138098 request.
