### ISSUE TITLE
Add templating to compile configs based on installation script arguments

### ISSUE THREAD

**Issue by dmitryax** [signalfx/splunk-otel-collector#298]
Currently, during installation process, collector agent+gateway and fluentd configurations are used as static files with optional recommended changes commented out. We need a way to compile configuration files based on installation command arguments.

We have two cases for now, more likely to be added:
- Adding a default `deployment.environment` attribute
- Run collector as an agent pointed to a gateway instead of the backend.

**Comment by jrcamp** [comment]
I think most of these could be done with config file merging/config sources but not necessarily worth being blocked on.

**Comment by rmfitzpatrick** [comment]
@dmitryax is this something you think is still needed, and if so do you have a suggested interface or implementation? I get the impression it's related to helm chart use cases but am not sure.
