### ISSUE TITLE
Re-check all the components included in this distribution

### ISSUE THREAD

**Issue by bogdandrutu** [signalfx/splunk-otel-collector#3]

**Comment by flands** [comment]
@jrcamp we use Prometheus receiver to gather collector's own metrics. These also need to be tagged a specific way and we need to drop grpc metrics. Is there a path forward with simpleprometheus receiver?

**Comment by jrcamp** [comment]
@flands There is but I haven't had a chance to test it. The filtering that's currently done inside the prometheus receiver needs to be moved to a processor.
