### ISSUE TITLE
Fail the build if `make generate finds change`

### ISSUE THREAD

**Issue by atoulme** [signalfx/splunk-otel-collector#3005]
Should we add a new github job/step to run `make generate-metrics` and fail if there are uncommitted changes, similar to https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/.github/workflows/build-and-test.yml#L184?

_Originally posted by @jeffreyc-splunk in https://github.com/signalfx/splunk-otel-collector/issues/2668#issuecomment-1518060538_

**Comment by jeffreyc-splunk** [comment]
Added `generate-metrics` job to github workflow in #3007.
