### ISSUE TITLE
Include sshcheck receiver from contrib

### ISSUE THREAD

**Issue by zchef2k** [signalfx/splunk-otel-collector#3050]
Please consider including ["sshcheck" from contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/sshcheckreceiver). This would help provide explicit down detection in Observability IM.

**Comment by atoulme** [comment]
This receiver is currently marked as in development. Have you used it? Did it fulfill your use cases?

**Comment by zchef2k** [comment]
I [forked this repo](https://github.com/zchef2k/splunk-otel-collector/tree/3050_include_contrib_sshcheck) yesterday and included the bits to include sshcheck. Forgive me if I've missed something, this is my first time working with Go and with this project.

The receiver works like I expect based on the documentation with one exception- the resource attribute for the metrics, which in this case is name of the endpoint being monitored, doesn't seem to emerge with what is collected. Perhaps   that's due to [this line?](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/84f2e450f21ce2e9ee9c0b64b28bd958fe8d7e6c/receiver/sshcheckreceiver/internal/metadata/generated_metrics.go#L80) I could open an issue in the contrib repo for better understanding of how this and other receivers work, in general.

![image](https://user-images.githubusercontent.com/743910/235891810-d2f18bac-8123-4ff9-b149-c3eca7d8a6e2.png)

**Comment by atoulme** [comment]
I have replied there.

**Comment by atoulme** [comment]
I have filed https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/21488 to follow up and make sure the component is at least alpha before we include it.

**Comment by atoulme** [comment]
I have gone ahead and entered your enhancement request into https://ideas.splunk.com/ideas/SFXIMMID-I-484 for review. Thanks!

**Comment by zchef2k** [comment]
Thank you, @atoulme. Can the votes I have on an existing idea help push things?

https://ideas.splunk.com/ideas/SFXIMMID-I-450?

**Comment by atoulme** [comment]
Yes it would. I'll close mine and adopt yours.

**Comment by atoulme** [comment]
Let's continue on the idea record directly. Thanks!

**Comment by zchef2k** [comment]
> Let's continue on the idea record directly. Thanks!

Not much happening on that end. Any chance you can help advocating internally?
