### ISSUE TITLE
Puppet 8x support

### ISSUE THREAD

**Issue by flepoutre** [signalfx/splunk-otel-collector#3147]
Hi,
I have tested the module on puppet 8x and we have there errors : 
`Error: Facter: Error while resolving custom fact fact='local_groups', resolution='<anonymous>': undefined method exists?' for File:Class
Error: Facter: Error while resolving custom fact fact='local_users', resolution='<anonymous>': undefined method exists?' for File:Class
`

Is it possible to fix it with a new Tag ?

File.exists? => File.exist?

Thanks,

**Comment by atoulme** [comment]
Thank you for your report. It appears this is tied to your underlying version of Ruby, as this method was renamed and removed in 2.3.0. Would you please share your OS as well?

**Comment by flepoutre** [comment]
Hi,
Yes that's fine.
I tested it on CentOS 7 but after I plan to reinstall the platform maybe on Ubuntu 22.04.
Thanks.

**Comment by atoulme** [comment]
It looks like we could make a modest attempt by replacing occurrences of File.exists? with File.exist? as a first step.

**Comment by atoulme** [comment]
If this works for you, I am tempted to close this as done. We can have a separate enhancement request to support Puppet 8.x with a Splunk idea. I have gone ahead and filed it for you: https://ideas.splunk.com/ideas/SFXIMMID-I-485 
We can continue the conversation over there and I will close this ticket. Thanks!

**Comment by flepoutre** [comment]
Hello,
We have this type of error too in Puppet 8x : 
<code>
Unknown variable: '::osfamily'.
</code>

**Comment by atoulme** [comment]
@flepoutre we're moving to Splunk ideas to prioritize enhancements, would you please upvote and report that it's not working?
