### ISSUE TITLE
Fluentd agent hanging when stopping v4.3.2 as pulled by the installer script

### ISSUE THREAD

**Issue by colsomerford** [signalfx/splunk-otel-collector#3181]
Windows 11, when stopping the td-agent service as part of the Collector restart the service hangs in a stopping state. Only fix is a full system reboot

splunk-otel-collector-0.77.0-amd64.msi
td-agent-4.3.2-x64.msi

Config for the td-agent is default as installed.
Receiver is the local Splunk Otel Collector listening on the default port.
Exporter is a SPLUNK_HEC endpoint to a Splunk Enterprise V9 install

**Comment by atoulme** [comment]
Sorry to hear you are encountering difficulties. Please follow up with a support case through this [link](https://splunk.my.site.com/customer/s/need-help/create-case), thanks!
