### ISSUE TITLE
Puppet module : adding possibility to set multiple groups ?

### ISSUE THREAD

**Issue by flepoutre** [signalfx/splunk-otel-collector#3188]
Hi,
Would it be possible to add in the puppet module (here => https://github.com/signalfx/splunk-otel-collector/blob/main/deployments/puppet/manifests/collector_service_owner.pp) the possibility to add multiple groups when the "splunk-otel-collector" user is created ?

For example, it's a prerequisite when we used the Varnish plugin => https://docs.splunk.com/Observability/gdi/varnish/telegraf-varnish.html

For example (maybe add optionnal "extra_group" parameters ?) : 
`user { $service_user:
        ensure => present,
        system => true,
        shell  => $shell,
        groups => [$service_group, $extra_group],
      }
`

Thanks,

**Comment by atoulme** [comment]
Sorry for the lateness in replying here. Please make sure to open an idea on [https://ideas.splunk.com](https://ideas.splunk.com). We will review internally this request and get back to you.

**Comment by h0tw1r3** [comment]
@flepoutre you can add this to your manifest code to ensure additional groups are added to the user:

```puppet
User <| tag == 'splunk_otel_collector::collector_service_owner' |> {                                                                                                                                        
  groups +> $service_group,                                                                                                                                                                                 
}
```
