### ISSUE TITLE
Upstream Pivotal Cloud Foundry assets to the OTel repos

### ISSUE THREAD

**Issue by cartersocha** [signalfx/splunk-otel-collector#3278]
In reference to this issue: https://github.com/open-telemetry/opentelemetry-collector/issues/5644

We would be interested in having these capabilities available in the vanilla OTel repos

**Comment by cartersocha** [comment]
CC: @smithclay @jaronoff97

**Comment by atoulme** [comment]
Great! We would be happy to facilitate. Please let us know how you would like to proceed.

**Comment by tylerbenson** [comment]
Can you submit it as a PR to the collector repo?

I'm not clear on how this is supposed to work.  Are customers required to build the collector and push to their PCF environment, or is it prebuilt and they just download it?

**Comment by cartersocha** [comment]
@atoulme is there a list of assets that could potentially be donated or is this a single integration? Our preferred deployment method would be to have a [community integration Tanzu tile](https://docs.splunk.com/Observability/gdi/opentelemetry/deployments/deployments-pivotal-cloudfoundry.html#pivotal-cloud-foundry)

**Comment by crobert-1** [comment]
I'll attempt to provide some context, a general overview of work necessary, and some of the possible challenges.

The Tanzu Tile of the Splunk distribution of the OpenTelemetry Collector works by passing variables into a BOSH release of the collector, and running that in the TAS environment. This means that both the BOSH release and Tanzu Tile functionalities would have to be moved.

There are also a few Splunk-specific parts of these distributions, especially the collector's exporter configuration. The exporter configuration is done through variables defined in the BOSH release, and then passed in from the Tanzu Tile, so there's some integration done that would have to be modified for a vanilla distribution.

Another part of the process is creating a Tanzu Tile that can be made available on the Tanzu Network. For testing the tile developers need access to a Tanzu environment. The call out I have here is that I'm not sure if Pivotal has some agreement with CNCF or the open source community for demo use of TAS environments, as I'm accessing them as a Splunk employee. Also, there's a whole release process required for new Tanzu Tiles that had an amount of company to company interaction, so I'm not sure how that translates to being able to release a tile from the open source community. These are unknowns to me though, so they may not be an issue.

I'll see if I can share specific documentation on what's required for new Tanzu Tiles and let you know.

**Comment by ctlong** [comment]
Hey @cartersocha, could you please describe in more depth the problem you're trying to solve?

FWIW Cloud Foundry (and by extension, TAS) is interested in integrating the OpenTelemetry Collector for aggregate metric egress, and beyond. See the following RFC: https://github.com/cloudfoundry/community/pull/641.

**Comment by cartersocha** [comment]
At a high level we're trying to make it easy to deploy an OTel collector on PCF to collect metrics and logs using a community or 1P owned asset. There is no pre-existing 1P support for OTel (would love to collaborate on that and the PR you linked) and the community itself doesn't support PCF deployment. 

However, Splunk does have a pre-existing Tanzu tile, BOSH scripts, etc. to deploy a Collector easily on PCF and they've graciously offered to donate those assets. So we were/are pursuing taking a 3P solution and upstreaming it to the community so the OTel project itself has a simple integration for PCF.

**Comment by ctlong** [comment]
Gotcha, thanks for the clarification. We (on the Cloud Foundry side) are currently motivated to try and add 1P support for OTel, and the PR I linked represents a first step in that direction. We'd appreciate all the collaboration we can get 😁. A sanity check on our proposal and future-looking advice would be awesome! Right now we're particularly curious about:
* Settings to use when running a Collector at scale on-VM.
* How we might go about garnering support for implementing some form of hot reloading for the Collector configuration, which we think would be necessary for app/space/org-level logs, metric and trace egress.

Let me know if I can help provide documentation or contacts for the asset donation if y'all keep working on that. As Curtis called out in his comment, there's a big difference between providing a BOSH release, and providing a Tanzu Tile on the Tanzu Network, at least for TAS. I'm also not super familiar with what that process looks like for the open source community though, but I can ask around.

**Comment by cartersocha** [comment]
Based on your linked proposal it seems like the bosh release and Tanzu tile may be unnecessary if every VM has a Collector already running? Pending expanding it to support traces / logs / more app data ingestion. 

We definitely help provide some guidance on running the Collector at scale. You've probably seen this but here's a link to the [current official otel scaling docs](https://opentelemetry.io/docs/collector/scaling/). Hot reloading has come up before in the Collector but there hasn't been a huge appetite for it yet. Have yall engaged in the otel-collector slack channel or other otel channels at all?

**Comment by ctlong** [comment]
> Based on your linked proposal it seems like the bosh release and Tanzu tile may be unnecessary if every VM has a Collector already running?

That's right.

> here's a link to the [current official otel scaling docs](https://opentelemetry.io/docs/collector/scaling/).

Thanks for sharing! I haven't looked through that before. Much of does appear k8s-specific. The `otelcol_exporter_` metrics info may prove useful though.

> Hot reloading has come up before in the Collector but there hasn't been a huge appetite for it yet. Have yall engaged in the otel-collector slack channel or other otel channels at all?

We attended a Collector SIG meeting a month or so back to pitch the idea. Definitely didn't seem like there was a huge appetite for the feature, but it also didn't seem like anyone was strongly against it 🤷. Since then we've mostly had hot reloading on the backburner as we worked on the proposal I linked to.

IIRC the outcome from that meeting was:
* See if there's a possibility for an "exportercreator" along the lines of the [receivercreator](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/receivercreator).
* If not, create a proposal on the Collector via GH issue to add hot reloading.
* Drive out that proposal as necessary.

Since the Collector uses a directed graph data structure under-the-hood to store each pipeline there might be room for a smaller change such that a reload which only added/removed leaf nodes (exporters) from pipelines could be done in a hot fashion. I think that would be the minimum we'd want, but might be too unambitious to gain traction.

**Comment by cartersocha** [comment]
Exciting to hear. We'd love to go deeper on this which would probably simpler with a call. Would you / your team be willing to chat? We can discuss yalls current plan, provide feedback, and sync on general goals etc. We have several Collector maintainers / contributors that can help.

**Comment by atoulme** [comment]
We have had further discussions and a solution is emerging in direct collaboration with VMWare from what I hear. We can close this issue at this time.
