### ISSUE TITLE
Security issue - default agent install should not bind to unrestricted IP address

### ISSUE THREAD

**Issue by dgcom** [signalfx/splunk-otel-collector#3375]
## Problem

Default installation of the Splunk OTEL agent contains configuration causing collector to bind up to 13 different ports on unrestricted IP address of 0.0.0.0

Example of the affected config file: https://github.com/signalfx/splunk-otel-collector/blob/main/cmd/otelcol/config/collector/agent_config.yaml

## Guidance

This is against security guidelines in the upstream project, details are outlined here: [Safeguards against denial of service attacks](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/security-best-practices.md#safeguards-against-denial-of-service-attacks)

There is also reference available to the Common Weakness Enumeration security site: [CWE - CWE-1327: Binding to an Unrestricted IP Address (4.12)](https://cwe.mitre.org/data/definitions/1327.html)

Additional reading - issue discussion: [Provide a mechanism to disable the 0.0.0.0 bind address warning · Issue #6938 · open-telemetry/opentelemetry-collector · GitHub](https://github.com/open-telemetry/opentelemetry-collector/issues/6938)

## Workaround

Manually edit configuration of the agent after the install (not scalable).
Wrap installation with script which fixes the issue after installation (extra work required).

## Suggested solution

All listeners for the default, local agent installation should bind to 127.0.0.1 (localhost).

Exceptions should be consciously selected at the time of the installation, for example - installing OTEL gateway should require specific list of listeners to be bound to the interface which allows external connections.

**Comment by atoulme** [comment]
Addressed with https://github.com/signalfx/splunk-otel-collector/pull/3421. Next release will have the change.

**Comment by dgcom** [comment]
I appreciate that Splunk team promptly started to address this issue, however I do not agree that this should not be reported here - this is not a vulnerability issue - and policy only requires separate reporting for those.

I am also taken aback by the lockdown of the issues section here - this is public, open source project and community should have an ability to open issues regardless if they have a support contract or not.

**Comment by atoulme** [comment]
@dgcom we don't have the ability to service issues properly on this repository and we want to make sure folks use support because it scales much better than our team when it comes to answering questions. We also try as much as possible to push our contributions upstream to the open-telemetry projects. Feel free to reach out to your account team and discuss further.

**Comment by dgcom** [comment]
> @dgcom we don't have the ability to service issues properly on this repository and we want to make sure folks use support because it scales much better than our team when it comes to answering questions. We also try as much as possible to push our contributions upstream to the open-telemetry projects. Feel free to reach out to your account team and discuss further.

I understand the challenge, but this approach is going against FOSS principles - to be open.
Sad to see issues locked to only people with support contract.
