### ISSUE TITLE
Pod labels for splunk source and sourcetype overwrite not being respected 

### ISSUE THREAD

**Issue by saiharshitachava** [signalfx/splunk-otel-collector#3424]
We installed the latest version of 0.81.0 chart and I see the custom pod labels to overwrite splunk source and scourctype isnt working but the index is working

I know the docs say we need to switch to annotations

But is there a back door (may be not via helm) to do this source and sourcetype overwrite from custom pod labels?

**Comment by rmfitzpatrick** [comment]
I believe this is a helm chart concern and your existing issue should be adequate for tracking: https://github.com/signalfx/splunk-otel-collector-chart/issues/862.

Unless there is problem determined to exist in a component developed in this repo this issue shouldn't be necessary.
