### ISSUE TITLE
Ansible role

### ISSUE THREAD

**Issue by xp-1000** [signalfx/splunk-otel-collector#352]
Hello,

looking to replace the signalfx smart agent by the new opentelemetry collector I would like to know if you plan to bring an ansible role similar to https://github.com/signalfx/signalfx-agent/tree/main/deployments/ansible like you did with https://github.com/signalfx/splunk-otel-collector-chart for https://github.com/signalfx/signalfx-agent/tree/main/deployments/k8s/helm/signalfx-agent ?

thanks

**Comment by rmfitzpatrick** [comment]
@xp-1000, thanks for raising this issue.  We will definitely support all the configuration management providers currently offered by the Smart Agent with this project, and I believe our Ansible role targeting linux is in active development.

**Comment by xp-1000** [comment]
Hello @rmfitzpatrick thanks for your answer and the good news.

Don't hesitate if you need early tester.

have a good day

**Comment by dmitryax** [comment]
Hi @xp-1000 , the first version of the role published as part of this ansible collection https://galaxy.ansible.com/signalfx/splunk_otel_collector

Feel free to try it, and let us know how it works. For now, it supports linux hosts only.

**Comment by dmitryax** [comment]
I'm closing the issue since we have Ansible role now. @xp-1000 if you run into any problems using it, please submit another issue
