### ISSUE TITLE
Be able to run otel validate command

### ISSUE THREAD

**Issue by cvauvarin** [signalfx/splunk-otel-collector#4173]
Hi,

It seems that the upstream OpenTelemetry Collector has a `validate` command that validates the config without running the collector. This command is not available when using the Splunk OpenTelemetry Collector and would be useful in order to improve the way the collector is started via systemd. As of today if the configuration contains errors and we restart the collector, the collector is stopped but will not start again and systemd will not catch the return code (due to the nature of the systemd service type : `simple`), using the validate command before restarting the collector can fix this behavior.

Thanks.

Charles

**Comment by rmfitzpatrick** [comment]
@cvauvarin you can use the `--dry-run` option to output the config, which should also show any validation errors as a workaround until we adopt the option.

**Comment by cvauvarin** [comment]
@rmfitzpatrick correct me if I am wrong but the `--dry-run` only validate the yaml syntax but not if the configuration is fully valid for otel. I managed to get a wrong configuration where `--dry-run` show the configuration and exit with a status code of 0 but the collector cannot start with a `Error: failed to get config: cannot unmarshal the configuration`.

**Comment by rmfitzpatrick** [comment]
My mistake, I misremembered the resolver flow. Adopted by https://github.com/signalfx/splunk-otel-collector/pull/4175
