### ISSUE TITLE
what config and where to add to start monitoring services from otel agent.

### ISSUE THREAD

**Issue by RPooja08** [signalfx/splunk-otel-collector#446]
We are trying to add the windows services config in yaml file for otel agent. But looks like I am not adding correct config code to yaml file. Please suggest the same.

I added as below, but not getting metrics data.

receivers:
signalfx:
smartagent/memory:
type: telegraf/memory
smartagent/win_services:
type: telegraf/win_services
serviceNames:
- Spooler

**Comment by mstumpfx** [comment]
Hello @RPooja08 😃 
Have you taken a look at our [Smart Agent --> Splunk Otel Collector Agent migration guide](https://github.com/signalfx/splunk-otel-collector/blob/main/docs/signalfx-smart-agent-migration.md)? 
You will need to make sure you are adding each respective receiver to your service pipeline definitions - [an example](https://github.com/signalfx/splunk-otel-collector/blob/main/cmd/otelcol/config/collector/agent_config.yaml#L160)

**Comment by RPooja08** [comment]
Yes, I did but I am not getting any data to SFX with this.

**Comment by mstumpfx** [comment]
That log message implies your receivers are defined under a `receiver_creator and not just `receivers`-  can you double check this? A full config would be better to look at than the snippet.

**Comment by RPooja08** [comment]
Yes, I am able to do the things, but how we can populate the custom metrics. I have tried the same way but looks like there issue.

I am getting the below error in application logs:

Problem running SQL query or converting datapoints

Stack Trace:

**Comment by mstumpfx** [comment]
@RPooja08 Can you post your full config with your sensitive information redacted please?

**Comment by RPooja08** [comment]
Hi, @mstumpfx Thank you so much for your guidance, I am able to do the correct configurations.
