### ISSUE TITLE
Windows service data is not reflecting.

### ISSUE THREAD

**Issue by RPooja08** [signalfx/splunk-otel-collector#466]
I am monitoring the MSSQL database service via otel agent.  I am getting other service data only having issue withis service. I am getting the below error in the windows events log.

Error:
"an error was emitted from the plugin

Stack Trace:
"
Below is the config added:

receivers:
  smartagent/win_services:
    type: telegraf/win_services
    serviceNames:
      - MSSQL$SQLEXPRESS
      -  Spooler

Kindly assist the same.

**Comment by zsiebers** [comment]
Was this issue ever resolved? I am having a similar issue

**Comment by RPooja08** [comment]
Yes it is resolved now.
