### ISSUE TITLE
Splunk HEC Reciever

### ISSUE THREAD

**Issue by domeger** [signalfx/splunk-otel-collector#503]
I would like to the ability to have OTEL act as a proxy HEC receiver that translate everything to Splunk Metric (SaaS). This would allow for native monitoring of AIX and third party solutions that can already read over TCP and reduce the need to install agent on every box in the environment. 

Currently I am having to do two types of methods to convert to Splunk Metrics from Splunk Cloud or a HF.

Method 1: Python Wrapper scrapping NMon and shipping to Splunk Cloud via HEC than using toSFX to convert to metrics using a Schedule Report every 60 seconds.

Method 2: Python Wrapper scrapping NMon and shipping to a HF with HEC than using toSFX to ship metrics every 60 seconds via Cronjob.

Expected Result: Eliminate the need for a Splunk Cloud or HF to accept HEC traffic.

**Comment by jrcamp** [comment]
I don't quite understand. Is there a Splunk Metric protocol? Is it open source?

**Comment by atoulme** [comment]
@domeger the OpenTelemetry Collector supports ingesting HEC today, and supports ingesting specifically metric data.
Please refer to https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/splunkhecreceiver and please let us know if this satisfies your requirements.

**Comment by atoulme** [comment]
This is now supported. Closing this issue, please open a new issue if further functionality is required.
