### ISSUE TITLE
Add zipkin as an exporter

### ISSUE THREAD

**Issue by markfink-splunk** [signalfx/splunk-otel-collector#58]
This is useful for sending traces to Splunk Enterprise.

**Comment by flands** [comment]
@markfink-splunk recommendation to sending to Splunk Enterprise is to use the HEC exporter: https://github.com/signalfx/splunk-otel-collector/blob/9e46f8d9ab7fa63c0af7c0539b7fb3ab27aee347/internal/components/components.go#L21
