### ISSUE TITLE
Link not working in Description

### ISSUE THREAD

**Issue by AchimGrolimund** [signalfx/splunk-otel-collector#709]
https://github.com/signalfx/splunk-otel-collector/blob/3391aa16ac0c44b54b80d1cec8ccae5cb998743a/cmd/otelcol/config/collector/full_config_linux.yaml#L190

Hey there, the link in thes Description runing to an 404 page not found.

https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor/resourceprocessor

Greetings Achim

**Comment by mstumpfx** [comment]
Thanks for pointing this out! I just updated all the links to be valid in that file.
