### ISSUE TITLE
Lots of extra warning in the logs about dimension length that aren't helpful

### ISSUE THREAD

**Issue by csydvs** [signalfx/splunk-otel-collector#719]
I'm running the splunk-otel-collector (updated to 0.34.1 and still seeing this functionality) as a side-car in a fargate task, and I'm seeing a bunch of warnings in my logs that look something like this:
```
warn translation/converter.go:475 dropping dimension {"kind": "exporter", "name": "signalfx", "reason": "dimension value longer than 256 characters", "dimension_value": "[\"arn:aws:logs:us-east-1:0123456789:log-group:/microservices/train-car:log-stream:service-config/service-config/6cbf79b745514d1eb70347f3e5b5aae2\",\"arn:aws:logs:us-east-1:0123456789:log-group:/microservices/train-car:log-stream:envoy/envoy/6cbf79b745514d1eb70347f3e5b5aae2\"]", "dimension_value_length": 277}
```
For context, there are several containers running as a part of my task, envoy is one of them (doing normal envoy activities), and service-config is a container that basically just downloads the splunk-otel-javaagent-all.jar to provide to my main service, and then exits. However, even after it has exited, I still get these warning logs. I'm not entirely sure what dimension involves concatenating these two containers log-groups together, but the logs are noisy. I could, of course, change
```
          resourcedetection:
            detectors: [ecs]
            override: false
```
to include an empty array, but I don't necessarily want to move away from the default fargate config without really understanding what these resource detectors are trying to pick up here.

Any help would be much appreciated.

**Comment by mstumpfx** [comment]
Hi @csydvs 

From what I can tell, it looks like you are correct that the ECS resource detection processor is generating these attributes longer than 256 characters causing them to be dropped (attributes are converted to signalfx dimensions). It looks to me like they're coming from [this section of code](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/ac26625c2eea420d6703a15e9bd81d686fb5b8af/processor/resourcedetectionprocessor/internal/aws/ecs/ecs.go#L152-L178) which concating all the containers in the task to create the log group ARNs.

In terms of workarounds to reduce noise, you _could_ just drop this dimension all together. I'm not sure what value it provides. I do think you probably want to keep the `resourcedetection` processor enabled for other metadata, but you should be able to use [the resource processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourceprocessor) with a `delete` action on the attribute name. Based on the dimension name I think it would be [one of these attributes](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/ac26625c2eea420d6703a15e9bd81d686fb5b8af/processor/resourcedetectionprocessor/internal/aws/ecs/ecs.go#L107-L112) which map to [these strings](https://github.com/open-telemetry/opentelemetry-collector/blob/main/model/semconv/v1.5.0/resource.go#L170-L208).

Not being able to tell the dimension name seems a little shortsighted on our end, I'll open a PR to add that to the log statement.

**Comment by mstumpfx** [comment]
Opened https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5258 to help identify the attributes key going forward.

**Comment by csydvs** [comment]
@mstumpfx Just a quick follow up on this, I added this at the bottom of my processors list:

```
          resource/remove_bad_dimension:
            attributes:
              - action: delete
                key: aws.log.stream.arns
              - action: delete
                key: aws.log.group.arns
              - action: delete
                key: aws.log.stream.names
              - action: delete
                key: aws.log.group.names
```
And then under `service.pipelines.traces.processors` I've added `resource/remove_bad_dimension` at the beginning of the list, but I'm still seeing these error logs. Do you have any other ideas for me?

**Comment by mstumpfx** [comment]
@csydvs that sounds correct to me, it may be helpful to post your config (feel free to redact anything unrelated) and we can vet it.

**Comment by mstumpfx** [comment]
@csydvs in your metrics pipeline you have the `resource/remove_bad_dimension` defined _before_ the `resourcedetection`, and I believe these things are processed in order they are defined. Can you try moving it to the end like you have in the traces pipeline?

**Comment by csydvs** [comment]
Ah, that was the key. Thanks!
