### ISSUE TITLE
Dangerous "delete_files" configuration

### ISSUE THREAD

**Issue by bogdandrutu** [signalfx/splunk-otel-collector#743]
I saw this option here: https://github.com/signalfx/splunk-otel-collector/tree/main/internal/configsource/includeconfigsource#configuration

The problem with this is that in case of a restart (reload config, or k8s restart) the collector will not be able to start since the file is no longer available.

I think this should be documented, or removed (if not strongly necessary).

**Comment by atoulme** [comment]
We will take this up internally, I will close this issue for now.
