### ISSUE TITLE
Using deprecated OTLP HTTP port

### ISSUE THREAD

**Issue by flands** [signalfx/splunk-otel-collector#764]
See https://github.com/signalfx/splunk-otel-collector/blob/aa8f4ad0ffeb2c4b6423de36de5d495dab54a6c0/cmd/otelcol/config/collector/agent_config.yaml#L70 needs to be `4318` -- what will migration strategy be?

**Comment by flands** [comment]
@pmcollins are you working on this?

**Comment by dmitryax** [comment]
Closed by https://github.com/signalfx/splunk-otel-collector/pull/1017
