### ISSUE TITLE
Document for all default otel metrics

### ISSUE THREAD

**Issue by RPooja08** [signalfx/splunk-otel-collector#995]
Hi All,

I am looking for any document where I can get the description of the default otel collector e.g.: otelcol_scraper_errored_metric_points

**Comment by TylerHelmuth** [comment]
I would like this as well.  I noticed if I add the logging exporter with loglev=debug I can see some descriptions, but that does feel like a real solution.

**Comment by atoulme** [comment]
We would typically follow the metrics here:
https://github.com/open-telemetry/opentelemetry-specification

Additionally, we maintain a mapping of our metrics to the smart agent here: https://docs.splunk.com/observability/gdi/opentelemetry/legacy-otel-mappings.html

Closing the issue, please reopen if you have further questions.
