### ISSUE TITLE
Unable to get pod level related content to show up in APM

### ISSUE THREAD

**Issue by notcool11** [signalfx/splunk-otel-collector#998]
So, following the guidance here:
https://docs.splunk.com/Observability/get-started/relatedcontent.html#splunk-apm

Says we will get the related content tiles for Clusters right away, which is working well. However, after selecting the cluster we are supposed to get the node and pod level tiles as well, but we are not.

Here are the tags that the Collector is supposed to add:
host.name
k8s.cluster.name
k8s.node.name
k8s.pod.name
container.id
k8s.namespace.name
kubernetes.workload.name

Here are the tags that show up on a Span:

<img width="358" alt="proccessTagsForCorrelations" src="https://user-images.githubusercontent.com/30246418/144121402-95c68732-39cf-4176-8151-185fa45dcd4e.png">

Notice that container.id and kubernetes.workload.name don't show up. Not sure if that is the problem??

Even so, I would expect the node and pod tiles to show up. Here you can see filtering to the cluster and in Tag Spotlight I can see node and pod information that is on the Span:

<img width="632" alt="tagSpotlightMissingCorrelations" src="https://user-images.githubusercontent.com/30246418/144121671-606ac7ac-1093-47af-b0ea-7cdfffb19bb7.png">

What is confusing is if I add a filter for the Node or Pod I can get the corresponding related content tile to show up. But this shouldn't be necessary as Node and Pod names are unique to the Cluster right?? In fact in this simple app there is just one cluster, one node and one pod, so I'd expect to see all the related content for all the items.

Furthermore, if I manually dig up the Pod Name and/or Container Id in Splunk IM, I will get the APM related content tile. So I can get to the APM service from IM pretty easily but not from APM to IM. Very confused, thanks for any help.

**Comment by emaderer** [comment]
@notcool11 is this still an issue?

**Comment by notcool11** [comment]
@emaderer , this can be closed. there was a combination of bad data on our side and bad configuration of APM/IM. all good now, thanks.
